/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/get-involved'
    | '/programs'
    | '/blog/$slug'
    | '/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/get-involved'
    | '/programs'
    | '/blog/$slug'
    | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/get-involved'
    | '/programs'
    | '/blog/$slug'
    | '/events/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRouteWithChildren
  GetInvolvedRoute: typeof GetInvolvedRoute
  ProgramsRoute: typeof ProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRouteWithChildren,
  GetInvolvedRoute: GetInvolvedRoute,
  ProgramsRoute: ProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
